namespace Roler.Toolkit.File.Mobi.Entity
{
    public enum MobiType : uint
    {
        Unkown,

        /// <summary>
        /// Mobipocket Book.
        /// </summary>
        Mobipocket = 2,

        /// <summary>
        ///  PalmDoc Book.
        /// </summary>
        PalmDoc = 3,

        /// <summary>
        /// Audio.
        /// </summary>
        Audio = 4,

        /// <summary>
        /// mobipocket? generated by kindlegen1.2.
        /// </summary>
        Mobipocket_Kindlegen_1_2 = 232,

        /// <summary>
        /// generated by kindlegen2.
        /// </summary>
        KF8 = 248,

        News = 257,

        News_Feed = 258,

        News_Magazine = 259,

        PICS = 513,

        WORD = 514,

        XLS = 515,

        PPT = 516,

        TEXT = 517,

        HTML = 518,
    }
}
